import { createHash } from 'node:crypto';
import { readdirSync, readFileSync, writeFileSync } from 'node:fs';
import { relative, resolve } from 'node:path';
import { defineConfig, type Plugin } from 'vite';

type ManifestEntry = {
  file: string;
  css?: string[];
  assets?: string[];
  imports?: string[];
  dynamicImports?: string[];
};

const workerSource = (version: string, precache: string[]) => `/* Generated by vite.config.ts. Do not edit. */
const VERSION = ${JSON.stringify(version)};
const PRECACHE = ${JSON.stringify(precache)};
const removeStaleCaches = () => caches.keys().then((keys) => Promise.all(keys.filter((key) => key.startsWith('arc-') && key !== VERSION).map((key) => caches.delete(key))));

self.addEventListener('install', (event) => {
  event.waitUntil(caches.open(VERSION).then((cache) => cache.addAll(PRECACHE)));
  self.skipWaiting();
});

self.addEventListener('activate', (event) => {
  event.waitUntil(Promise.all([
    removeStaleCaches(),
    self.clients.claim()
  ]));
});

self.addEventListener('fetch', (event) => {
  if (event.request.method !== 'GET') return;
  const url = new URL(event.request.url);
  if (url.origin !== self.location.origin) return;
  event.waitUntil(removeStaleCaches());

  if (event.request.mode === 'navigate') {
    event.respondWith(fetch(event.request).catch(async () => (await caches.match(event.request, { ignoreVary: true })) || (await caches.match('/index.html', { ignoreVary: true })) || caches.match('/offline.html', { ignoreVary: true })));
    return;
  }

  event.respondWith(caches.match(event.request, { ignoreVary: true }).then((cached) => cached || fetch(event.request).then((response) => {
    if (response.ok && ['style', 'script', 'image', 'font'].includes(event.request.destination)) {
      const copy = response.clone();
      caches.open(VERSION).then((cache) => cache.put(event.request, copy));
    }
    return response;
  })));
});
`;

function publicFiles(directory: string): string[] {
  return readdirSync(directory, { withFileTypes: true }).flatMap((entry) => {
    const path = resolve(directory, entry.name);
    if (entry.isDirectory()) return publicFiles(path);
    const file = relative(resolve(process.cwd(), 'public'), path).replaceAll('\\', '/');
    // Azure Static Web Apps consumes this deployment-only file; it is not a public URL.
    return file === 'staticwebapp.config.json' ? [] : [`/${file}`];
  });
}

function generatedServiceWorker(): Plugin {
  return {
    name: 'arc-generated-service-worker',
    closeBundle() {
      const output = resolve(process.cwd(), 'dist');
      const manifest = JSON.parse(readFileSync(resolve(output, '.vite/manifest.json'), 'utf8')) as Record<string, ManifestEntry>;
      const files = new Set<string>();
      const visit = (key: string) => {
        const entry = manifest[key];
        if (!entry || files.has(entry.file)) return;
        files.add(entry.file);
        entry.css?.forEach((file) => files.add(file));
        entry.assets?.forEach((file) => files.add(file));
        [...(entry.imports ?? []), ...(entry.dynamicImports ?? [])].forEach(visit);
      };
      Object.entries(manifest).filter(([, entry]) => entry.file.endsWith('.js')).forEach(([key]) => visit(key));

      const precache = [...new Set(['/', '/index.html', ...publicFiles(resolve(process.cwd(), 'public')), ...files].map((file) => file.startsWith('/') ? file : `/${file}`))].sort();
      const version = `arc-${createHash('sha256').update(`${Date.now()}\n${precache.join('\n')}`).digest('hex').slice(0, 12)}`;
      writeFileSync(resolve(output, 'sw.js'), workerSource(version, precache));
    },
  };
}

export default defineConfig({
  build: {
    target: 'es2022',
    outDir: 'dist',
    sourcemap: true,
    manifest: true,
  },
  plugins: [generatedServiceWorker()],
});
